<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\windows.graphics.capture\windows.graphics.capture.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\windows.graphics.capture\windows.graphics.capture.vcxproj" />
  </ItemGroup>

  <Target Name="CopyCppDll" AfterTargets="Build">
    <Copy SourceFiles="..\x64\$(Configuration)\windows.graphics.capture.dll" 
          DestinationFolder="$(OutDir)" 
          SkipUnchangedFiles="true" />
  </Target>

</Project>
