<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>EtwSnap.WpaPlugin</AssemblyName>
    <RootNamespace>EtwSnap.WpaPlugin</RootNamespace>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.21" />
    <PackageReference Include="Microsoft.Performance.SDK" Version="1.2.2-preview">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="pluginManifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>